[package]
name = "mini_os"
version = "0.1.0"
edition = "2021"

[dependencies]

# Disable Unwinding Stack Variables on Panic by Default

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"