[package]
name = "mini_os"
version = "0.1.0"
edition = "2021"

# Use a premade bootloader (implemented in rust and assembly NOT C code) instead of implementing it outselves
# bootloaders are responsible for initializing the CPU and loading our custom Kernel
# versions 0.11.x of the bootloader crate is broken and 0.10.x requires additional research to work

[dependencies]
bootloader = "0.9.22"