# Recompile compiler builtins and core library because it comes precompiled only for specific targets, not custom ones

# Also include the mem feature set of compiler builtins which include memory functions like "memcpy, memset and memcmp"
# Which are typically included by the C library on the host OS, but we need to either implement it outselves or use existing features (which we are doing here)

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# Custom target --> for no host OS
# - Don't unwind for panics (abort instead), use LLD as the linker instead for cross-compatibility
# - Disable redzone optimization to avoid annoying errors / bugs later on, use x86-64 architecture
# - Disable SIMD to increase performance, use soft-float (software implementation) for floating point numbers instead of SIMD

[build]
target = "x86_64-mini_os.json"

# This `runner` executable does 2 things: uses the cargo `bootimage` crate / command to build the bootimage and link the kernal together
# It then uses qemu to emulate a x86_64 machine and use the newely created bootimage as the boot drive and runs our OS
# Same thing can be done by executing these commands:
# - `cargo bootimage` (which does `cargo build` under the hood)
# - `qemu-system-x86_64 -drive format=raw,file=target/x86_64-mini_os/debug/bootimage-mini_os.bin`

[target.'cfg(target_os = "none")']
runner = "bootimage runner"